### ISSUE TITLE
Update Handling of Takedown servers

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/ansible-playbooks#174]
## Overview
Currently, we basically ignore all takedown servers. This leaves them very outdated and not receiving bug updates. We should update the work flow so that we update takedown servers and then re-take them down. 

## Design or Proposal
Handle this by blanking out the mongo uri.

```
- name: Include getting wanted docker-compose files
  ...

- name: Create docker compose takedown yaml file
  ansible.builtin.copy:
    content: |
      version: "3.7"
      
      services:
        sia:
          environment:
            - MONGODB_URI=''
    dest: "{{ webportal_dir }}/docker-compose.takedown.yml"

- block:
    - name: Start just sia docker service
      community.docker.docker_compose:
        ...
        files: "{{ webportal_docker_compose_files_wanted + ['{{ webportal_dir }}/docker-compose.takedown.yml'] }}"
  always:
    - name: Remove docker compose takedown file
      ansible.builtin.file:
        path: "{{ webportal_dir }}/docker-compose.takedown.yml"
        state: absent
```

Notes from Discord
```
we create takedown yml for docker compose up,
after dc up we can clean it, because we don't need it for dc down
we need to test that for sia it's ok MONGODB_URI='' to be present and empty (vs not present in env vars at all) - sia not restarting every 30 secs or 1 min
block/always is like try/catch to remove takedown yml even when community.docker.docker_compose fails
```
